### ISSUE TITLE
Master branch not working with tutor

### ISSUE THREAD

**Issue by FatemeKhodayari** [openedx/frontend-app-discussions#584]
Hi. I'm running openedx palm 3 with tutor. When switching the discussions MFE to the master branch, after launch, I get this page:

![fc855bc0de8bf78905148bb6929a458cc62b1fa2](https://github.com/openedx/frontend-app-discussions/assets/55655542/e6d91e88-9887-40ba-b9a2-b77584e1764e)

The said line is ```const { params: { page } } = useRouteMatch(`${Routes.COMMENTS.PAGE}?`);```. So I assume that the `useRouteMatch` function is returning null. Can you please help me with this?

This issue was first [posted in the forum](https://discuss.openedx.org/t/discussion-mfe-not-working-on-master-branch/11369).

**Comment by xitij2000** [comment]
I've investigated this and it's happening because frontend-platform sets the [basename for the browser history](https://github.com/openedx/frontend-platform/blob/6bb07c9cceb5c875f8a45ea32a1f165caef7c050/src/initialize.js#L100-L103) to the PUBLIC_PATH which is [set to the application name in tutor](https://github.com/overhangio/tutor-mfe/blame/b28f25b7f6ac053e9e4b0db565d5907b9fc02923/tutormfe/templates/mfe/build/mfe/Dockerfile#L75).

What this means it that the discussions MFE is trying to match paths starting with `/discussions/... ` whereas frontend platform has already stripped those out.
